/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("io.quarkus")

}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val quarkusPlatformVersion: String by project
val quarkusPlatformArtifactId: String by project

dependencies {
    implementation(platform("io.quarkus:$quarkusPlatformArtifactId:$quarkusPlatformVersion"))
    implementation("io.quarkus:quarkus-arc-deployment")
    // FIPS Compliance
    implementation("org.bouncycastle:bctls-fips:1.0.18")
    implementation("org.bouncycastle:bc-fips:1.0.2.4")
    implementation("io.quarkus:quarkus-security")
    implementation("io.quarkus:quarkus-kubernetes-client")

    testImplementation("io.quarkus:quarkus-junit5")
}


// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.test {
}
